apiVersion: v1
kind: Service
metadata:
  name: okno-app-service
spec:

  ports:
  - nodePort: 30000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: okno-k8s
  type: NodePort
  externalIPs:
    - 0.0.0.0
